import type { Locale } from "@/lib/i18n";

const ru = {
  meta: {
    title: "Zukko Academy — английский, IT и подготовка к экзаменам в Ташкенте (демо)",
    description: "Демо-сайт учебного центра от CaravanHouse: курсы с фильтрами, тест уровня английского, расписание групп, запись на пробный урок и личный кабинет ученика.",
  },
  demo: { text: "Демо-сайт от CaravanHouse IT — учебный центр вымышленный, заявки никуда не отправляются.", cta: "Заказать такой сайт" },
  personal: {
    bar: "Демо от CaravanHouse IT — так может выглядеть сайт «{name}». Курсы ваши, остальное — для примера.",
    cta: "Хочу такое для своего центра",
    cardTitle: "Курсы центра",
    courseNote: "Здесь будет описание курса: программа, длительность, расписание и цена.",
    scheduleNote: "Пример расписания — на настоящем сайте здесь будут ваши группы и кабинеты.",
    stats: [
      { value: "{courses}", label: "направлений" },
      { value: "24/7", label: "запись онлайн" },
      { value: "1 мин", label: "на заявку" },
    ],
    footer: "Демо-сайт для «{name}» от CaravanHouse IT. Курсы — ваши, остальные данные — для примера.",
    homework: "Домашнее задание к уроку",
    subtitle: "{courses} — в одном месте: расписание групп, запись на пробный урок и личный кабинет ученика.",
  },
  nav: { courses: "Курсы", test: "Тест уровня", schedule: "Расписание", teachers: "Преподаватели", cabinet: "Личный кабинет" },
  langLabel: "Язык",
  trial: "Пробный урок",
  currency: "сум",
  perMonth: "сум / мес",
  hero: {
    badge: "Набор в осенние группы открыт",
    title: "Учитесь там, где",
    titleAccent: "видно результат",
    subtitle: "Английский, IT и подготовка к IELTS и SAT в мини-группах. Первый урок — бесплатно, прогресс и домашки — в личном кабинете.",
    cta: "Записаться на пробный урок",
    test: "Узнать свой уровень за 2 минуты",
    stats: [
      { value: "1 200+", label: "выпускников" },
      { value: "7.0", label: "средний IELTS" },
      { value: "до 8", label: "человек в группе" },
    ],
    card: { title: "Ближайший старт", seats: "Свободно мест:", start: "через", days: "дн" },
  },
  courses: {
    eyebrow: "Курсы",
    title: "Выберите направление",
    all: "Все",
    directions: { english: "Английский", it: "IT", school: "Школьникам", exams: "Экзамены" },
    formats: { offline: "Офлайн", online: "Онлайн" },
    anyFormat: "Любой формат",
    months: "мес",
    perWeek: "раза в неделю",
    seatsLeft: "Свободно мест:",
    startIn: "Старт через",
    days: "дн",
    teacher: "Ведёт",
    book: "Пробный урок",
    hit: "Популярный",
    empty: "Нет курсов с такими фильтрами",
  },
  test: {
    eyebrow: "Тест уровня",
    title: "Какой у вас уровень английского?",
    subtitle: "6 вопросов, 2 минуты. В конце — уровень по шкале CEFR и подходящий курс.",
    start: "Начать тест",
    question: "Вопрос",
    of: "из",
    resultTitle: "Ваш уровень",
    resultText: "правильных ответов. Рекомендуем курс:",
    again: "Пройти ещё раз",
    book: "Записаться на пробный",
  },
  schedule: {
    eyebrow: "Расписание",
    title: "Расписание групп на неделю",
    subtitle: "Нажмите на занятие, чтобы записаться на пробный урок в эту группу.",
    room: "Кабинет",
  },
  teachers: { eyebrow: "Преподаватели", title: "Учат практики", years: "лет опыта" },
  modal: {
    title: "Пробный урок бесплатно",
    course: "Курс",
    group: "Группа",
    name: "Имя",
    phone: "Телефон",
    age: "Для кого",
    ages: ["Для себя", "Для ребёнка"],
    send: "Записаться",
    required: "Укажите имя и телефон",
    successTitle: "Вы записаны на пробный урок!",
    successText: "Это демо — заявка никуда не отправлена. В настоящем сайте администратор перезвонил бы за 15 минут, а напоминание пришло бы в Telegram.",
    close: "Закрыть",
  },
  cabinet: {
    title: "Личный кабинет",
    hello: "Привет",
    subtitle: "Так ученик видит свою учёбу: прогресс, расписание, домашние задания и оплаты.",
    demo: "Вы вошли как демо-ученик",
    back: "← На сайт",
    progress: "Прогресс",
    lessons: "уроков",
    attendance: "Посещаемость",
    next: "Следующее занятие",
    homework: "Домашние задания",
    statuses: { todo: "Сделать", review: "На проверке", done: "Проверено" },
    due: { today: "сегодня", tomorrow: "завтра", past: "сдано" },
    payments: "Оплаты",
    paid: "Оплачено",
    unpaid: "К оплате",
    pay: "Оплатить",
    calendar: "Посещаемость за 4 недели",
    certificate: "Сертификат после курса",
  },
  footer: { about: "Zukko Academy — вымышленный учебный центр для демонстрации сайта.", made: "Сайт сделан командой CaravanHouse IT" },
};

export type UI = typeof ru;

const uz: UI = {
  meta: {
    title: "Zukko Academy — Toshkentda ingliz tili, IT va imtihonlarga tayyorgarlik (demo)",
    description: "CaravanHouse tayyorlagan oʻquv markazi demo-sayti: filtrli kurslar, ingliz tili darajasi testi, guruhlar jadvali, sinov darsiga yozilish va oʻquvchi shaxsiy kabineti.",
  },
  demo: { text: "CaravanHouse IT demo-sayti — oʻquv markazi oʻylab topilgan, arizalar hech qayerga yuborilmaydi.", cta: "Shunday sayt buyurtma qilish" },
  personal: {
    bar: "CaravanHouse IT demosi — «{name}» sayti shunday koʻrinishi mumkin. Kurslar sizniki, qolgani — namuna uchun.",
    cta: "Markazim uchun shunday sayt kerak",
    cardTitle: "Markaz kurslari",
    courseNote: "Bu yerda kurs tavsifi boʻladi: dastur, davomiylik, jadval va narx.",
    scheduleNote: "Jadval namunasi — haqiqiy saytda bu yerda sizning guruhlaringiz va xonalaringiz boʻladi.",
    stats: [
      { value: "{courses}", label: "yoʻnalish" },
      { value: "24/7", label: "onlayn yozilish" },
      { value: "1 daq", label: "ariza uchun" },
    ],
    footer: "«{name}» uchun CaravanHouse IT tayyorlagan demo-sayt. Kurslar — sizniki, qolgan maʼlumotlar — namuna uchun.",
    homework: "Darsga uy vazifasi",
    subtitle: "{courses} — bir joyda: guruhlar jadvali, sinov darsiga yozilish va oʻquvchi shaxsiy kabineti.",
  },
  nav: { courses: "Kurslar", test: "Daraja testi", schedule: "Jadval", teachers: "Oʻqituvchilar", cabinet: "Shaxsiy kabinet" },
  langLabel: "Til",
  trial: "Sinov darsi",
  currency: "soʻm",
  perMonth: "soʻm / oy",
  hero: {
    badge: "Kuzgi guruhlarga qabul ochiq",
    title: "Natija",
    titleAccent: "koʻrinadigan joyda oʻqing",
    subtitle: "Mini guruhlarda ingliz tili, IT hamda IELTS va SAT ga tayyorgarlik. Birinchi dars — bepul, natija va uy vazifalari — shaxsiy kabinetda.",
    cta: "Sinov darsiga yozilish",
    test: "Darajangizni 2 daqiqada bilib oling",
    stats: [
      { value: "1 200+", label: "bitiruvchi" },
      { value: "7.0", label: "oʻrtacha IELTS" },
      { value: "8 tagacha", label: "guruhda kishi" },
    ],
    card: { title: "Eng yaqin start", seats: "Boʻsh joylar:", start: "", days: "kundan keyin" },
  },
  courses: {
    eyebrow: "Kurslar",
    title: "Yoʻnalishni tanlang",
    all: "Hammasi",
    directions: { english: "Ingliz tili", it: "IT", school: "Maktab oʻquvchilari", exams: "Imtihonlar" },
    formats: { offline: "Oflayn", online: "Onlayn" },
    anyFormat: "Istalgan format",
    months: "oy",
    perWeek: "marta haftasiga",
    seatsLeft: "Boʻsh joylar:",
    startIn: "Start",
    days: "kundan keyin",
    teacher: "Oʻqituvchi",
    book: "Sinov darsi",
    hit: "Ommabop",
    empty: "Bunday filtrlar boʻyicha kurs yoʻq",
  },
  test: {
    eyebrow: "Daraja testi",
    title: "Ingliz tili darajangiz qanday?",
    subtitle: "6 ta savol, 2 daqiqa. Oxirida — CEFR shkalasi boʻyicha daraja va mos kurs.",
    start: "Testni boshlash",
    question: "Savol",
    of: "/",
    resultTitle: "Sizning darajangiz",
    resultText: "ta toʻgʻri javob. Tavsiya etilgan kurs:",
    again: "Qayta topshirish",
    book: "Sinov darsiga yozilish",
  },
  schedule: {
    eyebrow: "Jadval",
    title: "Haftalik guruhlar jadvali",
    subtitle: "Shu guruhdagi sinov darsiga yozilish uchun darsni bosing.",
    room: "Xona",
  },
  teachers: { eyebrow: "Oʻqituvchilar", title: "Amaliyotchilar oʻqitadi", years: "yillik tajriba" },
  modal: {
    title: "Bepul sinov darsi",
    course: "Kurs",
    group: "Guruh",
    name: "Ism",
    phone: "Telefon",
    age: "Kim uchun",
    ages: ["Oʻzim uchun", "Farzandim uchun"],
    send: "Yozilish",
    required: "Ism va telefonni kiriting",
    successTitle: "Siz sinov darsiga yozildingiz!",
    successText: "Bu demo — ariza hech qayerga yuborilmadi. Haqiqiy saytda administrator 15 daqiqada qoʻngʻiroq qilardi, eslatma esa Telegramga kelardi.",
    close: "Yopish",
  },
  cabinet: {
    title: "Shaxsiy kabinet",
    hello: "Salom",
    subtitle: "Oʻquvchi oʻqishini shunday koʻradi: natija, jadval, uy vazifalari va toʻlovlar.",
    demo: "Siz demo-oʻquvchi sifatida kirdingiz",
    back: "← Saytga",
    progress: "Natija",
    lessons: "dars",
    attendance: "Davomat",
    next: "Keyingi dars",
    homework: "Uy vazifalari",
    statuses: { todo: "Bajarish", review: "Tekshiruvda", done: "Tekshirildi" },
    due: { today: "bugun", tomorrow: "ertaga", past: "topshirildi" },
    payments: "Toʻlovlar",
    paid: "Toʻlangan",
    unpaid: "Toʻlanishi kerak",
    pay: "Toʻlash",
    calendar: "4 haftalik davomat",
    certificate: "Kursdan keyin sertifikat",
  },
  footer: { about: "Zukko Academy — saytni namoyish qilish uchun oʻylab topilgan oʻquv markazi.", made: "Sayt CaravanHouse IT jamoasi tomonidan yaratilgan" },
};

const dictionaries: Record<Locale, UI> = { ru, uz };
export const getUI = (lang: Locale) => dictionaries[lang];
